### ISSUE TITLE
incompatible with new web extensions / multiprocess firefox

### ISSUE THREAD

**Issue by Pomax** [lazierthanthou/sqlite-manager#81] opened 2017-07-14 17:47 UTC
With the new multiprocess Firefox, this addon no longer works.

![screenshot 222](https://user-images.githubusercontent.com/177243/28223874-e49d4826-6881-11e7-82a5-3c36d51059db.png)

**Comment by grahamperrin** [comment] 2017-08-23 02:11
Duplicate of [Migrate to WebExtensions, if it's possible. · Issue #75 · lazierthanthou/sqlite-manager](https://github.com/lazierthanthou/sqlite-manager/issues/75)

**Closed** 2017-08-29 17:28 UTC
